server:
  port: 20880
  ssl:
    key-password: 123456
    key-store-type: JKS
    key-store: classpath:qinzhijie.keystore
    key-alias: qzj
    enabled: true

    
spring:
  application: 
    name: qzj
    
    banner:
     charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
  messages: 
    encoding: UTF-8
    
  datasource:
    name: carutoo
    url: jdbc:mysql://127.0.0.1:3306/qinzhijie?useSSL=false
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:com/qzj/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.qzj.dto  # 注意：对应实体类的路径
  configuration:
    mapUnderscoreToCamelCase: true
    
    
logging:
  config: classpath:log4j2.xml 
  
  
  

system-params:
  port: 8080